---
name: Image deployment

#
# ┌──────┐   ┌───────┐   ┌────────┐   ┌──────────┐
# │ Test │   │ Build │   │Push to │   │Update K8s│
# │      ├──►│ Image ├──►│Registry├──►│manifests │
# └──────┘   └───────┘   └────────┘   └──────────┘
# 

on:
  release:
    types: [published]
  workflow_dispatch:


env:
  IMAGE_NAME: image-name
  REGISTRY_URL: registry.idener.ai


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-push:
    name: Build & push image
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
